# source: https://github.com/hashicorp/vault-guides/tree/master/identity/vault-agent-k8s-demo
# Create a service account, 'vault-auth'
# $ kubectl create serviceaccount vault-auth
# Update the 'vault-auth' service account
# $ kubectl apply --filename vault-auth-service-account.yml

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
